title: Lost and Found for UH Manoa
description: Centralized system for listing lost and found items at UH Manoa
google_analytics:
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/314isnotdefined/314isnotdefined.github.io
gems:
  - jekyll-mentions
